#!/usr/bin/env python3
"""Generate the staging pages from shared/build.xslt.

build.xslt is the single source of truth for the header and footer markup.
This script lifts that chrome out of it, swaps the Slate-absolute image paths
for relative ones, and wraps each demo fragment in tools/demo/ as a standalone
page. Run it after any change to the chrome:

    python3 tools/make-staging.py

Staging pages are generated files — edit build.xslt or the demo fragments,
never the generated HTML.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
XSLT = (ROOT / "shared" / "build.xslt").read_text()

PAGES = {
    "index.html": ("demo-form.html", "Request Information",
                   "Staging preview of Baker University's Slate branding — form page."),
    "portal.html": ("demo-portal.html", "Application Status",
                    "Staging preview of Baker University's Slate branding — portal page."),
}

FONTS = ('https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@'
         '0,6..72,300;0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,300;1,6..72,400'
         '&family=Roboto:wght@300;400;500;700&display=swap')


def lift(tag):
    start = XSLT.index(f'<{tag} class="site-{tag}')
    end = XSLT.index(f'</{tag}>', start) + len(f'</{tag}>')
    chunk = XSLT[start:end].replace('src="/images/', 'src="images/')
    # de-indent from XSLT nesting to page nesting
    return "\n".join(l[6:] if l.startswith(" " * 6) else l for l in chunk.split("\n"))


def build(out, fragment, title, description):
    demo = (ROOT / "tools" / "demo" / fragment).read_text().rstrip()
    demo = "\n".join(" " * 12 + l if l.strip() else l for l in demo.split("\n"))
    page = f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{title} | Baker University</title>
    <meta name="description" content="{description}">
    <meta name="robots" content="noindex,nofollow">

    <!-- Same families and weights requested in shared/build.xslt. -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{FONTS}">

    <!-- The SAME stylesheet that ships to Slate, not a staging copy of it. -->
    <link rel="stylesheet" href="shared/build.css">
</head>
<body>

    <!-- GENERATED by tools/make-staging.py — edit shared/build.xslt or
         tools/demo/{fragment}, then re-run the script. -->

    <a class="skip-link" href="#main-content">Skip to main content</a>

{lift('header')}

    <main id="main-content" class="slate-form-area" role="main">
        <div class="slate-form-area__inner">
            <div id="global"></div>
            <div id="content">

{demo}

            </div>
        </div>
    </main>

{lift('footer')}

</body>
</html>
"""
    (ROOT / out).write_text(page)
    return out, len(page.split("\n"))


if __name__ == "__main__":
    for out, (fragment, title, desc) in PAGES.items():
        name, lines = build(out, fragment, title, desc)
        print(f"wrote {name} ({lines} lines)")
